### ISSUE TITLE
Request: consuming empty comments and not adding extra spaces

### ISSUE THREAD

**Issue by jamesbraza** [geo7/mypy_clean_slate#101]
Running `mypy-clean-slate==0.2.5` and `mypy==1.8.0` on this:

```python
foo = "hi"
foo = 5  #
```

It leads to this:

```python
foo = "hi"
foo = 5    # type: ignore[assignment] #
```

I am requesting two fixes here:

- Extra spaces not get added before the comment
- The stray `#` to be consumed

Thank you in advance!

**Comment by geo7** [comment]
_> stray # to be consumed_

Re the stray `#`, I'll have a look at this but I feel this _might_ be out of scope. 

> Extra spaces not get added before the comment

Makes sense ! I seem to recall something around this a while back

**Comment by geo7** [comment]
See https://peps.python.org/pep-0008/#inline-comments re two spaces.

**Comment by jamesbraza** [comment]
Thanks for sharing PEP 8, I didn't realize the wording was ≥ 2 spaces, not exactly 2 spaces.

That being said, another major tool in Python ecosystem is `black`, which has resulted in a standard of two spaces before a comment: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#comments

So the issue with > 2 spaces after `mypy_clean_slate` is it interferes with `black`, which requires re-running `black` after running `mypy_clean_slate`. Ideally, `mypy_clean_slate` would either:

- Use exactly 2-spaces, to align with `black` (which most people use in tandem with `mypy`)
- Support an opt-in CLI flag `--black` to enable this 2-spaces

What do you think?

**Comment by geo7** [comment]
Makes sense - added change here: https://github.com/geo7/mypy_clean_slate/pull/113

> Support an opt-in CLI flag --black to enable this 2-spaces

Maybe an `--inline-comment-space=2` or something might make sense at some point - but I think having 2 spaces fixed is fine atm.
