### ISSUE TITLE
Request: accommodating `poetry` based dependencies

### ISSUE THREAD

**Issue by jamesbraza** [geo7/mypy_clean_slate#103]
For people using `poetry`, one has to do `poetry run mypy`.

When invoking `poetry run mypy_clean_slate -ra`, it prints:

```
Generating mypy report using: mypy . --show-error-codes --no-pretty --strict
```

Which won't work because it needs to be `poetry run mypy ...`.

The request is, can we add a flag or configuration option so the tool will utilize `poetry run` to call `mypy`

**Comment by geo7** [comment]
Thanks - Yeah this makes sense - a work around would be to run `poetry shell` first, or to install it using `pipx`, but I'll have a look at implementing something a bit nicer for this case :)

**Comment by geo7** [comment]
@jamesbraza can you add an example of the error you get from this please?

**Comment by jamesbraza** [comment]
Sure here is a rough one. This is the set up:

```bash
pipx install poetry
poetry install  # Without mypy_clean_slate
poetry add mypy_clean_slate
mypy  # Not found, cuz didn't invoke poetry run mypy
```

Now the actual usage: `poetry run mypy_clean_slate -ra`.

Imo this won't work because `mypy_clean_slate` is just subprocess calling `mypy .`

Does that make sense?

**Comment by geo7** [comment]
@jamesbraza It would be helpful if you could create an error for this :) 

if you create a file with `subprocess.run('which python', shell = True)` it might be instructive though.
