### ISSUE TITLE
Allow removing unused type: ignore?

### ISSUE THREAD

**Issue by eyurtsev** [geo7/mypy_clean_slate#106]
Would be great to get functionality to remove unused type ignore. I know it's likely not in scope, but would be pretty useful since the tool is already able to apply changes from the report per line

**Comment by geo7** [comment]
Makes sense, feels kinda out of scope but it is something mypy reports so kinda in scope as well :smile: I'll have a look over the weekend

**Comment by jamesbraza** [comment]
This would be really useful! I also agree with this request.

My workaround for this has been manually running a regex removal of `# type: ignore`, then invoking `mypy_clean_slate`. I agree it would be nice if built-in to `mypy_clean_slate`
