### ISSUE TITLE
0.1.6 not on PyPi

### ISSUE THREAD

**Issue by codekiln** [geo7/mypy_clean_slate#69]
I see that this project has updated the mypy constraint to `mypy = ">=0.910,<1.8"` in 0.1.6, but that is not published to PyPi yet. Kindly consider publishing it. 

```
pip-compile etc/requirements-dev.in --output-file=etc/requirements-dev.txt
Could not find a version that matches mypy-clean-slate>=0.1.6 (from -r etc/requirements-dev.in (line 77))
Tried: 0.1.2, 0.1.2, 0.1.3, 0.1.3, 0.1.4, 0.1.4, 0.1.5, 0.1.5
There are incompatible versions in the resolved dependencies:
```

Side question - is this project also useful for those that are not using `--strict`?

**Comment by geo7** [comment]
> Kindly consider publishing it.

Thanks - will do :+1: 

> is this project also useful for those that are not using `--strict`

Short answer : maybe

Longer answer: It's aimed towards getting a project in a state that `--strict` can be used. If you ran this and then used a more permissive set of mypy flags some of the added ignores would most likely be redundant. If there are only a few to remove it might be fine, if there are loads it could be more annoying. That being said - it shouldn't be hard to update `mypy_clean_slate` to accept a particular set of flags and generate ignores for those (eg, if only using `--disallow-untyped-defs` and `--disallow-incomplete-defs` or whatever). 

Reasoning for this was that the projects I've worked on have sometimes struggled to get into a state that `--strict` can be used, but using `--strict` has been preferred if possible (which `mypy_clean_slate` tries to facilitate).

**Comment by geo7** [comment]
@codekiln that's updated fwiw (there's no `0.1.6` , increased from `0.1.5` -> `0.2.0` when dropping 3.8 support). 

Will close this now - feel free to open a different issue if there's anything else though
