### ISSUE TITLE
Updating `mypy_clean_slate --help` in `README`

### ISSUE THREAD

**Issue by jamesbraza** [geo7/mypy_clean_slate#87]
The current `README.md`'s Usage section: https://github.com/geo7/mypy_clean_slate/tree/79b62c1bb7bb9f2cbe97cf6d0a69aae68632120c?tab=readme-ov-file#usage

Seems to lag the actual usage, as it lacks the `--path_to_code` option

**Comment by geo7** [comment]
Ah ok will update, cheers.
